language: python
python:
    - 3.5
install: 
    - pip install unittest2
    - pip install pyrebase
    - pip install urllib3
script: python YardiBackOfficeManager/YardiProcessManager/DataManagerTDD.py
